### ISSUE TITLE
Manual Flashing Procedure references bad URLs

### ISSUE THREAD

**Issue by nskaggs** [danielewood/sierra-wireless-modems#10]
The manua flashing procedure is linking to some now missing URLs (for example, wget http://security.ubuntu.com/ubuntu/pool/universe/libq/libqmi/libqmi-utils_1.20.0-1ubuntu1_amd64.deb
). I think it would be best to actually just update everything to cosmic as it has the required newer packages in the archive. Baring that, we can update the links to point to a ppa or something more stable; or really ideally, find a better distribution method. Thanks for documenting all of this!

**Comment by rob235** [comment]
Hi Daniel. The same problem occurs in the automated script and so of course it fails. Looking forward to your update. By the way I was using the script on an EM7430 which has a VID:PID of 1199:907b
thanks for your efforts.

**Comment by danielewood** [comment]
Resolved by #13
