### ISSUE TITLE
Script failed to download FW, and manual install failed with "error: couldn't open QMI device: Failure"

### ISSUE THREAD

**Issue by Krivers29** [danielewood/sierra-wireless-modems#127]
Hello,

I'm using Ubuntu 22.04 LiveUSB and I want to flash my EM7455 (DW5811e).
Autoflash_7455.sh failed at function download_modem_firmware(), $SWI9X30C_URL is empty : 

![Capture d’écran du 2022-06-30 15-37-04](https://user-images.githubusercontent.com/108478308/176718481-d7132187-45ce-4d89-8be6-c2dfce2e1ff2.png)

I tried to manually flash instead by following your procedure, and I get this error : 

![Capture d’écran du 2022-06-30 15-43-09](https://user-images.githubusercontent.com/108478308/176719829-ab28d4a9-29a9-4c80-bf5f-6eaccb4ca067.png)

Am I doing something wrong? Do I need to get an older release of Ubuntu?

**Comment by Krivers29** [comment]
I used Sierra Wireless Linux Flashing Tool instead, it did the job.
But anyway I guess Sierra FW URL changed once again, could you update it?

**Comment by zaskokus** [comment]
@Krivers29 what command did you use for the Sierra Wireless Linux Flashing Tool ? did you have to do anything else besides running it?

**Comment by Krivers29** [comment]
@zaskokus well it turns out that I was in the same case as you with Sierra Wireless Linux Flashing Tool, but I didn't realized on the spot. My guess is that the modem is in NBIM mode and not QMI. You can try to switch it by sending AT commands on ttyUSB2.

But actually I went back and cheated by hard coding $SWI9X30C_URL and $SWI9X30C_ZIP in autoflash_7455.sh.


> also: i can see you're using 2.38 - I'm having major issues with this firmware. ModemManager doesn't want to connect to any network anymore.

I haven't manage to set up wwan setup yet, so it might be because of 2.38... I'll try flashing another FW next time .

**Comment by zaskokus** [comment]
> I haven't manage to set up wwan setup yet, so it might be because of 2.38... I'll try flashing another FW next time .

@Krivers29 I managed to get it working, but I had to manually send some commands to the modem to actually use proper configuration file for the 2.38 firmware (I was on 2.32 before). There's no benefit of upgrading beyond the first upgrade from the engineering sample thing.

**Comment by Krivers29** [comment]
@zaskokus To be more precise,WWAN was working on Windows before and after upgrade. Where I'm stuck is on my Syslink router
