### ISSUE TITLE
Autoflash not working cause Download URL changed

### ISSUE THREAD

**Issue by nightcat91** [danielewood/sierra-wireless-modems#130]
Hi,
i tried using the autoflash script on a Ubuntu 20.04 Live System.
It seems that everything works until it gets to the part where it wants to download the Generic Firmware.
Stops there cause of this error: https://github.com/danielewood/sierra-wireless-modems/blob/master/autoflash-7455.sh#L318

After looking around a bit I noticed that Sierra Wireless seemed to have changed the firmware website.
The correct URL would now probably be:
new: https://source.sierrawireless.com/resources/airprime/minicard/74xx/em_mc74xx-approved-fw-packages
old:  https://source.sierrawireless.com/resources/airprime/minicard/74xx/airprime-em_mc74xx-approved-fw-packages

But simply changing the URL in line 308 https://github.com/danielewood/sierra-wireless-modems/blob/master/autoflash-7455.sh#L308
did not work.
I think the whole part about the Download URL and filename needs a few tweaks, but sadly I cant figure out whats wrong.

Would be nice if that could be upgraded!?

**Comment by Habibi6989** [comment]
im having same issue

**Comment by Bublikhead** [comment]
Yep, same. Any advice?

**Comment by Habibi6989** [comment]
this is a stupid solution i used. you can update it using by downloading the zip file from sierra then unzip and specify the path.
here is the link for the forked script
https://github.com/Habibi6989/sierra-wireless-modems.git

autoflash-7455.sh has been modified read the first few lines in the comments

**Comment by Bublikhead** [comment]
Looks like it worked, but haven't flashed yet. 

Flashing SWI9X30C_02.38.00.00.cwe onto Generic Sierra Modem...
reseter operation finished successfully
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
Found 413c:81b5
error: unknown firmware image file
Firmware Update failed, exiting...

I don't quite understand why it's unknown.

**Comment by Habibi6989** [comment]
are you using this image file "SWI9X30C_02.38.00.00" ? I'm thinking you might have setup the path wrong or there is some other issue. I haven't seen this error before, I will give it a try and maybe make a short video later today.

**Comment by Habibi6989** [comment]
also you could use this method:  https://www.thinkpenguin.com/gnu-linux/update-firmware-em7455-chip-and-set-device-id-sierra-wireless

you might need to add --device for the first command like the example below
sudo perl swi_setusbcomp.pl --device=/dev/cdc-wdm0 --usbcomp=6
