### ISSUE TITLE
T480/EM7455 confirmed working but need to block some pin

### ISSUE THREAD

**Issue by Richard-Tung** [danielewood/sierra-wireless-modems#24]
Need to block 29,31,35,37 pin(force to use USB 2.0 interface).
27,33,39 are GND pin so you can block it as well.
Maybe conflict with Motherboard PCIe pin?

Photos here:
https://forum.51nb.com/forum.php?mod=viewthread&tid=1900391

**Comment by danielewood** [comment]
I had forgot about this part. 

Please see if the following AT commands to set USB2 only will fix the issue without tape and I'll add them to my script defaults(zero real world benefit to USB3 on the 7455).

```
AT!ENTERCND="A710"
AT!USBSPEED=0
AT!RESET
```

**Comment by Richard-Tung** [comment]
But taped pin is still required for the first time.
Otherwise the device will not recognized by device manager.

**Comment by danielewood** [comment]
> But taped pin is still required for the first time.
> Otherwise the device will not recognized by device manager.

True, I need to add that users should buy a $10 NGFF to USB Adapters with SIM Card Slots, as that completely eliminates things like needing to hotswap while the laptop is sleeping.

I'll test these commands with some of my own modems and a USB3 enclosure next week and add that detail to the T480 section.

**Comment by danielewood** [comment]
The commands do work on the 7455, so I'll add them to my script defaults:

Before:
```
T:  Bus=04 Lev=01 Prnt=01 Port=01 Cnt=01 Dev#=  2 Spd=5000 MxCh= 0
D:  Ver= 3.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 9 #Cfgs=  1
P:  Vendor=1199 ProdID=9071 Rev= 0.06
S:  Manufacturer=Sierra Wireless, Incorporated
S:  Product=EM7455
C:* #Ifs= 5 Cfg#= 1 Atr=a0 MxPwr=504mA
A:  FirstIf#=12 IfCount= 2 Cls=02(comm.) Sub=0e Prot=00
I:* If#= 0 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=ff Prot=ff Driver=qcserial
E:  Ad=81(I) Atr=02(Bulk) MxPS=1024 Ivl=0ms
E:  Ad=01(O) Atr=02(Bulk) MxPS=1024 Ivl=0ms
I:* If#= 2 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=00 Prot=00 Driver=qcserial
E:  Ad=83(I) Atr=03(Int.) MxPS=  10 Ivl=32ms
E:  Ad=82(I) Atr=02(Bulk) MxPS=1024 Ivl=0ms
E:  Ad=02(O) Atr=02(Bulk) MxPS=1024 Ivl=0ms
I:* If#= 3 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=00 Prot=00 Driver=qcserial
E:  Ad=85(I) Atr=03(Int.) MxPS=  10 Ivl=32ms
E:  Ad=84(I) Atr=02(Bulk) MxPS=1024 Ivl=0ms
E:  Ad=03(O) Atr=02(Bulk) MxPS=1024 Ivl=0ms
I:* If#=12 Alt= 0 #EPs= 1 Cls=02(comm.) Sub=0e Prot=00 Driver=cdc_mbim
E:  Ad=87(I) Atr=03(Int.) MxPS=  64 Ivl=32ms
I:  If#=13 Alt= 0 #EPs= 0 Cls=0a(data ) Sub=00 Prot=02 Driver=cdc_mbim
I:* If#=13 Alt= 1 #EPs= 2 Cls=0a(data ) Sub=00 Prot=02 Driver=cdc_mbim
E:  Ad=86(I) Atr=02(Bulk) MxPS=1024 Ivl=0ms
E:  Ad=04(O) Atr=02(Bulk) MxPS=1024 Ivl=0ms

AT!USBSPEED=?
!USBSPEED: <max_supported_speed>
<max_supported_speed>:
  0 - High Speed
  1 - Super Speed

OK
AT!USBSPEED?
SUPPORTED:Super-Speed
CURRENT  :Super-Speed

AT!USBSPEED=0
OK
```

After:
```
T:  Bus=03 Lev=01 Prnt=01 Port=01 Cnt=01 Dev#=  3 Spd=480  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=1199 ProdID=9071 Rev= 0.06
S:  Manufacturer=Sierra Wireless, Incorporated
S:  Product=EM7455
C:* #Ifs= 5 Cfg#= 1 Atr=a0 MxPwr=500mA
A:  FirstIf#=12 IfCount= 2 Cls=02(comm.) Sub=0e Prot=00
I:* If#= 0 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=ff Prot=ff Driver=qcserial
E:  Ad=81(I) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=01(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms
I:* If#= 2 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=00 Prot=00 Driver=qcserial
E:  Ad=83(I) Atr=03(Int.) MxPS=  10 Ivl=32ms
E:  Ad=82(I) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=02(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms
I:* If#= 3 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=00 Prot=00 Driver=qcserial
E:  Ad=85(I) Atr=03(Int.) MxPS=  10 Ivl=32ms
E:  Ad=84(I) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=03(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms
I:* If#=12 Alt= 0 #EPs= 1 Cls=02(comm.) Sub=0e Prot=00 Driver=cdc_mbim
E:  Ad=87(I) Atr=03(Int.) MxPS=  64 Ivl=32ms
I:  If#=13 Alt= 0 #EPs= 0 Cls=0a(data ) Sub=00 Prot=02 Driver=cdc_mbim
I:* If#=13 Alt= 1 #EPs= 2 Cls=0a(data ) Sub=00 Prot=02 Driver=cdc_mbim
E:  Ad=86(I) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=04(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms

AT!USBSPEED?
SUPPORTED:High-Speed
CURRENT  :High-Speed

OK
```

**Comment by danielewood** [comment]
Fix action from changes:
https://github.com/danielewood/sierra-wireless-modems/blob/README.md#bypass-lenovo-whitelist-for-t470carbon-x1-g6-and-other-newer-lenovo-laptops

### Bypass Lenovo Whitelist for T470/Carbon X1 G6 and other newer Lenovo laptops
Note: [Use a $10 M.2 USB Adapter to flash and configure the modem](https://www.ebay.com/sch/i.html?_from=R40&_nkw=ngff+sim+usb&_sacat=0&_sop=15)
1. Enable Advanced Commands:
    + `AT!ENTERCND="A710"`
2. Skip bootloader mode on warm-boots.
    + `AT!CUSTOM="FASTENUMEN",2`
    + Prevents device from showing up until it has been fully initialized. This causes the modem to stealth bypass BIOS whitelists as it will not show up until a few seconds after the BIOS has completed its checks.
3. Tell the modem to ignore the W_DISABLE pin sent by many laptop's internal M2 slots.
    + `AT!PCOFFEN=2`
4. Force USB2 mode to enable compatibility with newer M.2 interfaces
    + `AT!AT!USBSPEED=0`
    + The EM7455 cannot exceed USB2 interface speeds anyways, there is no performance loss.
5. Save settings and reboot modem to apply
    + `AT!RESET`

**Comment by kkursor** [comment]
My modem blamed an error on USBSPEED=0.
Solution:
1. Get firmware from https://source.sierrawireless.com/resources/airprime/minicard/74xx/em_mc74xx-approved-fw-packages/ (latest generic firmware, unzip)
2. deviceid=`lsusb | grep -i -E '1199:9071|1199:9079|413C:81B6' | awk '{print $6}'`

sudo qmi-firmware-update --update -d "$deviceid" SWI9X30C_02.33.03.00.cwe SWI9X30C_02.33.03.00_GENERIC_002.072_001.nvu
(put your CWE and NVU files)

3. Enjoy ^^,

Source: https://www.thinkpenguin.com/gnu-linux/update-firmware-em7455-chip-and-set-device-id-sierra-wireless

Writing this from ThinkPad T480 with Debian 12. Thanks, man!
