### ISSUE TITLE
Device stuck in QDLoader

### ISSUE THREAD

**Issue by syspringdawn** [danielewood/sierra-wireless-modems#25]
Hi Daniel,
I'm trying to recover an EM7455 that I got stuck in QDLoader mode. Following your notes and using an 18.04 image I see this device id in lsusb:

Bus 003 Device 010: ID 1199:9078 Sierra Wireless, Inc.

Then trying, with a bit of freelancing, the --update-qdl gets this:
ubuntu@ubuntu:~$ qmi-firmware-update --update-qdl -d 1199:9078 SWI9X30C_02.30.01.01.cwe SWI9X30C_02.30.01.01_GENERIC_002.045_000.nvu
error: error creating device: error opening serial device: Permission denied

Is this get out-able of ??

Tx

**Comment by danielewood** [comment]
> Then trying, with a bit of freelancing, the --update-qdl gets this:
> ubuntu@ubuntu:~$ qmi-firmware-update --update-qdl -d 1199:9078 SWI9X30C_02.30.01.01.cwe SWI9X30C_02.30.01.01_GENERIC_002.045_000.nvu
> error: error creating device: error opening serial device: Permission denied

Try with sudo since you are not a privileged user.

**Comment by syspringdawn** [comment]
Tried with sudo...
ubuntu@ubuntu:~$ sudo qmi-firmware-update --update-qdl -d 1199:9078 SWI9X30C_02.30.01.01.cwe SWI9X30C_02.30.01.01_GENERIC_002.045_000.nvu
error: error creating device: HDLC trailing control character not found

Having done a search on that error maybe this is beyond my skill to resolve. Oh well, I have another 7455 that your script succesfully updated and made generic - thankyou

**Comment by syspringdawn** [comment]
Now resolved, yay! It may be that running qmi update almost as soon as the device appears in lsusb is all thats necessary. It may be that help from a third party to set the protocol mode then reset the device did the trick. Whatever I now have working EM7455 with the latest firmware and set up as generic
