### ISSUE TITLE
Auto flash script fails at trying to pull FW from sierrra's website

### ISSUE THREAD

**Issue by cyberdev82** [danielewood/sierra-wireless-modems#49]
Hi @danielewood  Daniele & Team

Thank you very much for your contributions to the wireless LTE community in getting the EM7455 dell / lenovo to work as generic.

I have DW5811e and faced lot of issues using other methods, finally decided to try your Ubuntu Auto Flash script, using Live LTS 18 but the script when its trying to pull the FW from sierra's website fails - either their URL maybe is now changed / or it needs login? 

the error is something about file size not matched, would really appreciate if you can help with this.

I managed to get in USBCOMP=8 mode and manually reflashed using Sierra tool on windows but the auto flash script would be super for saving time in case it gets (EM7455) to DW5811e.

Thank you very much!

~James
netqatar8@gmail.com

**Comment by danielewood** [comment]
Resolved by #51
