### ISSUE TITLE
Stuck in boothold wait

### ISSUE THREAD

**Issue by maxguru** [danielewood/sierra-wireless-modems#76]
**Describe the bug**
I have an EM7445 which I flashed using the autoflash script over a year ago. Recently, it stopped connecting to the carrier, so, I thought maybe my firmware needs an update. I tried to use the autoflash script again, however, this time it gets stuck in the boothold wait.

```
...
Waiting for modem to reboot...
Already downloaded SWI9X30C_02.33.03.00_GENERIC_002.072_000.zip...
Archive:  SWI9X30C_02.33.03.00_GENERIC_002.072_000.zip
  inflating: SWI9X30C_02.33.03.00.cwe  
  inflating: SWI9X30C_02.33.03.00_GENERIC_002.072_000.nvu  
---
Flashing SWI9X30C_02.33.03.00.cwe onto Generic Sierra Modem...
reseter operation finished successfully
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
Waiting for modem in boothold mode...
...
```

**To Reproduce**
1. Permanently connect modem to VirtualBox VM in settings
2. Boot into Ubuntu Desktop 20.04 Live CD in VirtualBox
3. Open Terminal
4. Type 'wget https://raw.githubusercontent.com/danielewood/sierra-wireless-modems/master/autoflash-7455.sh && sudo bash autoflash-7455.sh'
5. See that it gets stuck waiting for boothold

**Expected behavior**
I expect it to finish the process.

**Desktop (please complete the following information):**
 - OS: Ubuntu Desktop 20.04
 - VirtualBox 6.1

**Additional context**
Worked perfectly last time using Ubuntu 18 Live CD and an older version of VirtualBox and the autoflash script.

**Comment by maxguru** [comment]
Apparently, my device ID is not in the list on this line: https://github.com/danielewood/sierra-wireless-modems/blob/0140710b28fd29658aa5e4277d6a08346bc543de/autoflash-7455.sh#L220

For my modem `lsusb` shows `1199:9071`. I tried adding that to the list of device IDs but now I get `error: unsupported download protocol`.

**Comment by danielewood** [comment]
1199:9071 is normal operation mode, not boot hold. 

I suspect the device id changing is causing your VM to not have it passed through, the 30second boot hold expires, then it reverts back to normal operation. 

You either need to pass in your entire USB controller, or also pass in the modem when it's in boothold (remember, short window, so you have to add it quick).

My real suggestion is to boot from a Ubuntu live usb, or use a raspberry pi running Ubuntu 20.04 or later. The last round of refactoring was all done on a Raspberry Pi as the host system.

**Comment by maxguru** [comment]
I finally got around to trying the upgrade on one of my Raspberry Pi's. I used Ubuntu 20.04 (64 bit). It seems to have worked. Thanks for the very helpful docs and the script!

**Comment by RomanGz** [comment]
Just in case anyone else ends up here, I got around this problem on a VM. Every time it would say "waiting for modem reboot", I would physically unplug & replug the usb cable,  as well as when it said "Waiting for modem in boothold". Finished to the end and is all good.
